# Generated by Django 2.2 on 2023-09-20 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20230920_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='appt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.appointmentsh'),
            preserve_default=False,
        ),
    ]
