# Generated by Django 2.2 on 2023-09-20 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_payment_appt'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=150, null=True)),
                ('appt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.appointmentsh')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.patientsh')),
            ],
            options={
                'db_table': 'Prescriptions',
            },
        ),
    ]
