# Generated by Django 2.2 on 2023-09-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_prescriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptions',
            old_name='payment',
            new_name='prescription',
        ),
    ]
