# Generated by Django 2.2 on 2023-09-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20230923_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund',
            field=models.BooleanField(default=False),
        ),
    ]
