# Generated by Django 2.2 on 2023-09-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_dynamicpanel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dynamicpanel',
            table='Dynamic_Panel',
        ),
    ]
