# Generated by Django 2.2 on 2023-09-23 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20230923_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicpanel',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.roles'),
        ),
    ]
