# Generated by Django 2.2 on 2023-09-23 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20230923_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicpanel',
            name='role1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicpanel',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.roles'),
        ),
    ]
