# Generated by Django 2.2 on 2023-09-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20230923_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicpanel',
            old_name='text',
            new_name='text1',
        ),
    ]
