# Generated by Django 2.2 on 2023-09-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20230923_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicpanel',
            name='role1',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
