# Generated by Django 2.2 on 2023-09-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20230925_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicpanel',
            old_name='role',
            new_name='rolea',
        ),
    ]
