# Generated by Django 2.2 on 2023-09-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20230925_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicpanel',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
