# Generated by Django 2.2 on 2023-09-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_dynamicpanel_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicpanel',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
