# Generated by Django 2.2 on 2023-09-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_dynamicpanel_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicpanel',
            old_name='order',
            new_name='order1',
        ),
    ]
