# Generated by Django 2.2 on 2023-09-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20230926_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicpanel',
            name='removed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
