# Generated by Django 2.2 on 2023-09-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_auto_20230926_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientsh',
            old_name='diastolic_bp',
            new_name='alcohol',
        ),
        migrations.RenameField(
            model_name='patientsh',
            old_name='heartrate',
            new_name='allergies',
        ),
        migrations.RenameField(
            model_name='patientsh',
            old_name='systolic_bp',
            new_name='diabetic',
        ),
        migrations.AddField(
            model_name='patientsh',
            name='drugs',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='patientsh',
            name='tobacco',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='patientsh',
            name='yourgender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
