# Generated by Django 2.2 on 2023-09-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_auto_20230928_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptions',
            name='advice',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='dosage',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='duration',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='symptoms',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='takingTime',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='tests',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
