# Generated by Django 2.2 on 2023-09-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_auto_20230928_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicpanel',
            name='icon',
            field=models.ImageField(blank=True, upload_to='Pictures/'),
        ),
    ]
