# Generated by Django 2.2 on 2023-09-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_dynamicpanel_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicpanel',
            name='icon',
            field=models.FileField(upload_to=''),
        ),
    ]
