# Generated by Django 2.2 on 2023-09-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_auto_20230928_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicpanel',
            name='icon',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
