# Generated by Django 2.2 on 2023-09-29 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_auto_20230928_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptions',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.patientsh'),
        ),
    ]
