# Generated by Django 2.2 on 2023-10-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_auto_20230930_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsh',
            name='yourgender',
            field=models.CharField(blank=True, default=1, max_length=10),
            preserve_default=False,
        ),
    ]
